kairan-app/feeeed

Dockerfile, Gemfile, Gemfile.lock, config/database.yml, docker-compose.yml
=> Docker Compose で起動できるようにする

app/models/user.rb, db/migrate/20240126153046_create_users.rb, db/schema.rb
=> Userモデルをつくる

app/models/channel.rb, db/migrate/20240127123627_create_channels.rb, db/schema.rb
ここでの Channel は「情報の湧き出し口」のような意味。実態として RSS/Atom のようなフィードを扱う。
ブログやポッドキャストや YouTube チャンネルの RSS/Atom を眺めて、下記のカラムを持たせてみることにした。
- title
- description
- site_link
- feed_link
- image_url
- セコンさんの日記
- https://secon.dev/feed
- 純朴声活 (ポッドキャスト番組)
- https://listen.style/p/juneboku-life/rss
- やんちゃクラブ (YouTube チャンネル)
- https://www.youtube.com/feeds/videos.xml?channel_id=UCn3T1nqjGuC40r_agfyF0Ag
- taizooo さんのブログ
- https://copyanddestroy.hatenablog.com/feed
- https://copyanddestroy.hatenablog.com/rss
=> Channel モデルをつくる

app/models/channel.rb, app/models/item.rb, db/migrate/20240127132259_create_items.rb, db/schema.rb
ここでの Item は、Channel の中の要素を表す。ブログにおける記事、ポッドキャスト番組におけるエピソード、YouTube チャンネルにおける動画などが Item になる。
=> Itemモデルをつくる

app/models/channel.rb, app/models/item.rb, app/models/user.rb, app/views/welcome/index.html.erb, db/migrate/20240126153046_create_users.rb, db/migrate/20240127123627_create_channels.rb, db/migrate/20240127132259_create_items.rb, db/schema.rb
- カラム名を考え直す
- 文字列カラムの最大長を考え直す
- これも必要だったわ、というカラムを追加する
=> テーブルのスキーマを見直す

app/controllers/channels_controller.rb, app/models/channel.rb, app/views/channels/show.html.erb, app/views/welcome/index.html.erb, config/routes.rb
Channel#fetch_and_save_items メソッドを実装し、Channel に属する Item の情報をデータベースに保存します。
このメソッドをいい感じのタイミングでバックグラウンドで実行することで、登録 Channel の新着情報にキャッチアップしていく想定です。
=> Item の情報を取得して保存する

.github/dependabot.yml
Dependabot を設定して bundle update を定常的に行うようにします :robot:
=> Dependabot を設定する

app/controllers/ownerships_controller.rb, app/controllers/users_controller.rb, app/models/channel.rb, app/models/ownership.rb, app/models/user.rb, app/views/channels/show.html.erb, app/views/layouts/_google_login.html.erb, app/views/ownerships/_link.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20240209091553_create_ownerships.rb, db/schema.rb
- Ownership モデルを実装する
- Channel に対して、ログイン中の User が「これを自分のものとして登録する」を行えるようにする
- User ページをつくって Owned Channels を表示する
- Channel の Owner は、今のところ「自己申告」でしかない
- 本当の Owner なのかを確認するスマートな手段はあるのか？
- 今のところは Channel ページに Owner を**表示しない**
=> Channel の持ち主を表現する Ownership モデルをつくる

config/routes.rb
こうやって書くとルーティング定義がわかりやすくなる気はする。どうでしょう？
=> ルーティング: パスはスラッシュはじまりで書く、インデントを揃えてみる

app/controllers/channels_controller.rb, app/controllers/items_controller.rb, app/controllers/users_controller.rb, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb
コントローラのアクションで `@title` を設定したらそれが反映される、という機構にしてみた :bulb:
=> HTML の title タグの中身を設定していく

app/controllers/subscriptions_controller.rb, app/controllers/users_controller.rb, app/models/channel.rb, app/models/concerns/channel_user_relation.rb, app/models/ownership.rb, app/models/subscription.rb, app/models/user.rb, app/views/channels/show.html.erb, app/views/subscriptions/_link.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20240211143648_create_subscriptions.rb, db/schema.rb
- 購読を表現する Subscription モデルを定義する
- Channel ページに「Subscribe」リンクを設置し、任意のチャンネルを購読できるようにする
- User ページには「Subscribed Channels」を表示する
- ひとまず、Channel ページに「Subscribers」は表示しない
- のちのち「Subscribers のうち、ログイン User が Follow している User だけ表示する」はアリかも？
=> Channel の購読を表現する Subscription モデルを実装する

app/controllers/application_controller.rb, app/controllers/channels_controller.rb, app/controllers/my/inbox_controller.rb, app/controllers/my_controller.rb, app/models/channel.rb, app/models/user.rb, app/views/channels/_form.html.erb, app/views/layouts/_flash_messages.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/application.html.erb, app/views/my/inbox/show.html.erb, config/routes.rb
- Channel を新規追加したら、トップページじゃなくて Channel ページにリダイレクトしよう
- ついでに Flash メッセージの表示処理もつくる
- グローバル・ナビゲーション的なものを設置するぞ
- グローバル・ナビゲーションに載せる項目のひとつとして Inbox ページを実装する
- Subscribe している Channel たちの新着 Item を新着順に表示する
=> 導線をちょっと整える @ 2024-02-12

lib/open_graph.rb
ひとつ前の Pull Request によって nil 例外を起こしうる実装になってしまったので、ちゃんと nil ガードします :bow:
- https://github.com/kairan-app/feeeed/pull/37
=> OpenGraph の nil 例外を出す実装を直す

app/assets/stylesheets/application.css, app/views/channels/_cards.html.erb, app/views/items/_cards.html.erb
=> スタイリング @ 2024-02-17

app/controllers/users_controller.rb, app/views/layouts/_menu.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb
一般公開時にも残るページになるかはわからないけれど、今のフェーズではあると便利なのでつくっちゃいます :yum:
=> User 一覧ページを用意する

app/jobs/item_creation_notifier_job.rb
Item の新着通知をする・しないのロジックをあれこれ考えて実装してきたが、よりシンプルで汎用的なひとつの条件を思い付いたので差し替えるぜ :v:
=> Channel 内で新しい方から 3 件以内の Item のみ新着通知する

app/assets/stylesheets/application.css, app/views/users/show.html.erb
「プロフィールアイコンは丸」のお作法に沿うようにしつつ、余白などの調整をしました🚀
=> スタイリング @ 2024-02-19

app/assets/stylesheets/application.css, app/views/channels/_cards.html.erb, app/views/layouts/_flash_messages.html.erb, app/views/layouts/application.html.erb, app/views/users/show.html.erb
headerを無くしてasideに集約しつつ、他にも少し整えたい🚀
=> スタイリング @ 2024-02-22

app/views/channels/_form.html.erb, app/views/layouts/_google_login.html.erb, app/views/layouts/application.html.erb
- https://github.com/kairan-app/feeeed/pull/68
は結局マージしなかったけれど、作業前の整理として取り組んだ https://github.com/kairan-app/feeeed/pull/68/commits/46c7e6c273b9124ab9e6e2473b180642990bdfbc は取り込んでおきたいので Cherry Pick する :cherries:
=> マークアップを少し整理する @ 2024-02-23

app/assets/stylesheets/application.css, app/controllers/items_controller.rb, app/controllers/my/inbox_controller.rb, app/controllers/my/reactions_controller.rb, app/controllers/reactions_controller.rb, app/controllers/welcome_controller.rb, app/jobs/reaction_creation_notifier_job.rb, app/models/item.rb, app/models/reaction.rb, app/models/user.rb, app/views/items/_cards.html.erb, app/views/items/_reaction.html.erb, app/views/layouts/_menu.html.erb, app/views/my/reactions/index.html.erb, app/views/reactions/_lines.html.erb, app/views/reactions/create.turbo_stream.erb, app/views/reactions/destroy.turbo_stream.erb, app/views/reactions/index.html.erb, config/routes.rb, db/migrate/20240223121712_create_reactions.rb, db/schema.rb
ここでは最低限の見た目で機能を実現するので、見せ方についてはたっぷり相談させてください :pray:
=> User が Item に対して「読んだ・観た・聴いた」を表現するための Reaction 機能を導入する

app/controllers/sessions_controller.rb, db/migrate/20240225042623_make_google_guid_column_unique_and_not_nullable.rb, db/schema.rb
- https://github.com/kairan-app/feeeed/pull/71
の続きをやります。メールアドレスを User の特定に使うのをやめて、Google が払い出してくれる ID を使うことにします。よっしゃ。
=> Google が払い出してくれる ID を User の特定に使う

app/assets/stylesheets/application.css, app/views/layouts/_menu.html.erb, app/views/reactions/index.html.erb
- Reactionsページのタイトル修正
- メニューアイコンをお試しで導入（アイコンは仮）
=> スタイリング @ 2024-02-26

app/controllers/my/profile_controller.rb, app/models/user.rb, app/views/layouts/_menu.html.erb, app/views/my/profile/show.html.erb, config/routes.rb, db/migrate/20240305145631_make_name_column_unique_on_users.rb, db/schema.rb
- User#name の編集機能をつくる
- User#name にユニーク制約を設定する (なんと、これまで未設定だった)
=> User#name を編集させてあげる

app/assets/stylesheets/application.css, app/views/layouts/_google_login.html.erb, app/views/layouts/_menu.html.erb
- スマホ表示でのメニューをハンバーガー化
- 上記に伴う微調整
- その他あれば
をやっていく🎨
=> スタイリング @ 2024-03-07

app/jobs/reaction_creation_notifier_job.rb, app/models/notification_webhook.rb, app/models/user.rb, db/migrate/20240312132505_create_notification_webhooks.rb, db/schema.rb
=> 直近の Reactions を Discord の Webhook で通知する機能を実装する

app/models/notification_webhook.rb
embeds は 10 個までしか指定できず、こえちゃうと Bad Request で通知に失敗するようだったので :yum:
=> Discord の Webhook で Reaction を通知するときは 10 件ずつにわけて処理する

app/jobs/item_creation_notifier_job.rb, app/jobs/reaction_creation_notifier_job.rb
- https://github.com/kairan-app/feeeed/pull/84
で Discord の embeds を使ってみたらグッドだったので、新着 Item 通知処理においても採用します :wink:
https://discord.com/developers/docs/resources/channel#embed-object
=> 新着 Item 通知も Discord の embeds を活用する

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/91
に似た話。Item の guid には entry_id を使いたいけれど、なければ url で代替しちゃおう。一意な値になるはず！
=> フィードの中の entry が entry_id を持っていない場合は url で代替する

app/assets/stylesheets/application.css, app/views/reactions/_lines.html.erb
Reaction一覧で以下を追加🎨
- Reaction主のアイコン表示
- メモがある場合はメモを表示
=> スタイリング @ 2024-03-17

app/assets/stylesheets/application.css
前回のやり残し＆ https://github.com/kairan-app/feeeed/issues/94#issuecomment-2002160470 でご指摘いただいた以下を修正🎨
- ユーザーアイコンは丸で統一したいけど四角くなっている
- スマホ表示の時に右側のpaddingが余計
- スマホ表示で下部UIがページャーなどを隠してしまう状態を解消
=> スタイリング @ 2024-03-18

app/assets/stylesheets/application.css, app/controllers/welcome_controller.rb, app/views/welcome/index.html.erb
トップページに Recent Pawprints を追加！🎨
=> スタイリング @ 2024-03-20

lib/disco.rb
- 使われなくなったメソッドを削除する
- ログ出力に [Disco] を付与してログを調べやすくしておく
=> Disco モジュールの細かいところを整える

app/controllers/channels_controller.rb, app/models/channel.rb, app/views/channels/show.html.erb, db/migrate/20240325124754_make_site_url_on_channels_not_required.rb, db/schema.rb
- Resolve https://github.com/kairan-app/feeeed/issues/92
=> Channel の site_url は存在しなくてもよいものとする

app/assets/stylesheets/application.css, app/views/layouts/_menu.html.erb
=> スタイリング @ 2024-03-26

app/assets/stylesheets/application.css, app/views/my/index.html.erb, app/views/my/notification_webhooks/index.html.erb, app/views/my/profile/show.html.erb
=> スタイリング @ 2024-03-28

config/initializers/session_store.rb
ウェブブラウザを閉じるたびにログアウトになっちゃうのは不便でしたね :pray:
=> ログインセッションは 1 週間有効とする

app/controllers/sessions_controller.rb
田舎の感覚で鍵をかけずに過ごしていたら人が入ってきたので、さすがに鍵をかけるか！となった :closed_lock_with_key:
=> ログインできるのは許可メールアドレスに載っている人だけ

app/assets/stylesheets/application.css, app/views/channels/_form.html.erb
メニューの項目数を減らす前段階の作業として実施🎨
（スマホ表示でのメニューをアプリっぽくフッタータブにするにあたり、一等地を占有している Channel 登録フォームさんに立ち退きしていただく🙏）
=> Channel登録フォームのスタイル変更

app/assets/stylesheets/application.css, app/views/channels/_search_form.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/application.html.erb, app/views/my/unreads/show.html.erb
気になっていたところを色々とスタイリング！
主に以下などを調整しています🎨
- アイコンがなんか太くて意図していなかったものを使っていたので、見直して調整
- スマホのフッター固定タブも調整（実機で触ってまた調整するかも？）
- 利用頻度は落ちたけどChannelsやItemsで使っていたナビゲーションを綺麗に
- Unreadsの冒頭のナビっぽいところも調整
=> スタイリング @ 2024-04-16

app/models/channel.rb, app/models/notification_webhook.rb
- https://github.com/kairan-app/feeeed/issues/127
こいつをやっていくです！ :v:
=> 新着 Item の Discord 通知、Channel でグルーピングする形にする

lib/disco.rb
=> Diso じゃなくて Disco よ

app/controllers/channels/fetch_controller.rb, app/views/channels/show.html.erb, config/routes.rb
- Resolve https://github.com/kairan-app/feeeed/issues/122
=> Channel ページに「更新して！」のリンクを置く

app/assets/stylesheets/application.css
主に、トップと Unreads ページでのマウスオーバーの挙動をわかりやすくしたのと、ヒーローエリアのスマホ表示の微調整などをしました！🎨
あと細かい数値の表記などで目についた揺れを直したりもしました（コミット分ければよかった、、、）
=> スタイリング @ 2024-04-26

config/environments/production.rb
- https://github.com/kairan-app/feeeed/pull/152
のブランチに Push したつもりが漏れていた Commit が手元に残っていたので、追い Pull Request します :dash:
=> Push 漏れしている Commit があったので、追い

app/controllers/notification_emails/verifications_controller.rb, app/controllers/notification_emails_controller.rb
=> NotificationEmail に関するイベントを運営 Discord に通知する

app/jobs/notification_email_notifier_job.rb, app/jobs/notification_webhook_notifier_job.rb, app/mailers/notification_email_mailer.rb, app/models/notification_email.rb, app/views/my/notification_settings/index.html.erb, app/views/notification_email_mailer/pawprints.text.erb, app/views/notification_email_mailer/subscribed_items.text.erb
- https://github.com/kairan-app/feeeed/pull/152
の続きをやっていきます！ NotificationWebhook と同様に、新着 Item と新着 Pawprint に対応させます :v:
=> NotificationWebhook のメール版をつくる - 実装編

app/controllers/notification_webhooks_controller.rb
- https://github.com/kairan-app/feeeed/pull/152
であれこれ統合したときに一通り古いパスを新しいパスに置き換えたつもりが、対応漏れがあった :pray: :sob:
=> 古いルーティングの置き換え漏れがあったので直す

app/controllers/pawprints_controller.rb
アルファ・リリースの準備の一環です :ok_hand:
- Pawprint は誰にどこまで見せることになるか、今後の意思決定に幅がある状態
- なので現時点では「積極的には公開しない」スタンスを取っておきたい
- 検索エンジンにもインデックスされたくない
=> Pawprint はログインしている人にだけ見せる

app/assets/stylesheets/application.css, app/views/channels/show.html.erb, app/views/subscriptions/_link.html.erb
いくつか検討したりしたけど結局以下の１つだけコミットしました🚀
- Channel ページで Subscribe ボタンをわかりやすく
（Subscribe した後は、そのことがわかるようなスタイルも追加）
=> スタイリング @ 2024-05-14

app/assets/stylesheets/application.css, app/views/channels/show.html.erb, app/views/ownerships/_link.html.erb
[前回のPR](https://github.com/kairan-app/feeeed/pull/185) で挙がっていた、Channel 詳細ページの追加スタイリングです💪
- Site と Feed の部分にアイコン追加
- 操作 UI 風の下の2つにもアイコン追加＆控えめにボタン化
=> スタイリング @ 2024-05-15

Dockerfile, Gemfile, Gemfile.lock
微妙に最新じゃない Ruby を使っていたので、思い立ったこのタイミングで最新バーンする :gem:
=> Ruby 3.3.1

app/assets/stylesheets/application.css, app/controllers/my/guides_controller.rb, app/models/user.rb, app/views/layouts/_menu.html.erb, app/views/my/guides/show.html.erb, config/routes.rb
初めて rururu を使う人に「こういうことをやってほしいのだよ」を示すために、活用ガイドのページを用意します :v:
=> 活用ガイドのページを用意する

app/controllers/channel_groupings_controller.rb, app/controllers/channel_groups_controller.rb, app/controllers/channels/preview_controller.rb, app/models/channel.rb, app/models/channel_group.rb, app/models/channel_grouping.rb, app/views/channel_groupings/_form.html.erb, app/views/channel_groups/index.html.erb, app/views/channel_groups/new.html.erb, app/views/channel_groups/show.html.erb, app/views/channels/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20240612062932_create_channel_groups.rb, db/migrate/20240612084547_create_channel_groupings.rb, db/schema.rb
- https://github.com/kairan-app/feeeed/issues/148
を実現していくぞ！この Pull Request では、キリのいいところまで進めるつもり :v:
=> Channel Group 機能を実装していく

app/controllers/channel_groups_controller.rb, app/views/channel_groups/show.html.erb, config/routes.rb
補完に頼りつつルーティング設定を忘れてて焦りつつ、やってみました💨
ご確認お願いします🙏
=> Channel Groupの名前を変更できるように

app/models/channel.rb, lib/open_graph.rb
- https://github.com/kairan-app/feeeed/pull/212
に書いたことはぼくの事実誤認によってよくわからん内容になってしまったので、実装を直していきます :pray: :dash:
=> フィード登録時のいろんなケースへの対応方法を間違えていたので修正する

app/controllers/my/unreads_controller.rb, app/models/user.rb, app/views/my/unreads/show.html.erb
Unreads ページに、自身が参加している ChannelGroup ごとに Item をリストしてくれるビューを実装します :muscle:
=> Unreads ページに、ChannelGroup のビューを追加する

app/assets/stylesheets/application.css, app/views/my/unreads/show.html.erb, app/views/welcome/index.html.erb
以下をスタイリングしました🎨
- UnreadsページのChannel Groupタブをスタイリング
- 前回のスタイリングで、channel-and-itemsコンポーネントの余白などに少しおかしな部分があったので修正
Channel Groupタブについては、「All / Text / Audio」との兼ね合いを引き続き模索したいと思っています！
（「All / Text / Audio」と共存するのか、「All / Text / Audio」を無くすかによっても変わってきそう）
=> スタイリング @ 2024-06-26

Dockerfile, Gemfile, Gemfile.lock
=> Ruby 3.3.3

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/228
によってバグを生じさせました :innocent:
=> entry.itunes_image は、当該タグが存在しないときには NoMethodError を起こすとのこと

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/228
の変更を加えてから Item の画像をうまく保存できなくなってしまった Channel がいくつかあったので、状況を調べた上で対処を行います :dash:
=> Entry の画像 URL の扱いをもっといい感じにする

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb, config/tailwind.config.js
ちょっとだけ進めました！
まだ手探りが続いています、慣れてきたらもう少しまとまった量を進めていきたい…🚀
=> スタイリング @ 2024-07-30

app/controllers/my/inbox_controller.rb, app/views/layouts/application.html.erb, app/views/my/inbox/show.html.erb, config/routes.rb
初期につくった Inbox ページであったが、今では Unread ページを育ててそこを常用してもらいたい意向なので、役目を終えたと判断してたたみます :pray:
=> Inbox ページを廃止する

app/controllers/channels_controller.rb, app/views/channels/show.html.erb
当たり前に求められることをサボっていたので、まじめにやりますね :joy:
=> Channel ページの Items をページングする

app/controllers/channel_groups_controller.rb, app/views/channel_groups/edit.html.erb, app/views/channel_groups/new.html.erb, app/views/channel_groups/show.html.erb, config/routes.rb
なにをどこまでやるか考えながら作業して、キリのいいところでマージしちゃお :dash:
- Channel の一覧を表示する (そんなに多くならないだろうし、全件でいいかなあ)
- Item を表示する (直近の数十件、とかでいいかなあ)
- 気になったところを手直しする、かも
=> ChannelGroup ページをちょっと整える

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb
- 日が経ってしまったので https://github.com/kairan-app/feeeed/pull/250 をこちらのPRにまとめました🙏
- 追加で footer を Tailwind CSS 化
=> スタイリング @ 2024-08-13

app/assets/stylesheets/application.css, app/views/channels/_cards.html.erb, app/views/items/_cards.html.erb, app/views/layouts/_flash_messages.html.erb, app/views/layouts/application.html.erb, app/views/my/index.html.erb, app/views/welcome/index.html.erb, db/schema.rb
いくつかの箇所をいじりました🚀
cardsのレイアウトについては、Tailwind CSS化する前にCSS自体を見直してまずコードをスッキリさせました！次回以降に同じ箇所のTailwind CSS化を進めます。
（インデントの調整もしたので余計なdiffがちょっと増えてしまったようです🙏）
=> スタイリング @ 2024-08-26

Dockerfile, Gemfile, Gemfile.lock
=> Ruby 3.3.5

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/274
の変更によって問題を生じさせていました :bow: :bow: :bow:
=> Item の image_url が '2' になってしまうバグを修正する

app/jobs/item_creation_notifier_job.rb, app/jobs/pawprint_creation_notifier_job.rb
そうすることで、より効率のよい役割分担ができるってことが経験から理解できた :v:
=> 最終的に Disco で通知を行うジョブは disco のキューを使う

app/models/channel.rb
ログを見ていたら nil, nil, nil って感じでほぼ情報ナシって感じになっていた。実装ミス。直します :sob:
=> 新着 Item のロギング処理をミスっていたので修正する

db/migrate/20240917151846_add_user_id_column_to_channel_group_webhooks_table.rb, db/schema.rb
ChannelGroupWebhook のための UI をつくるぞ！と思って作業を始めたら user_id カラムがなくてびっくり。急ごしらえで作ったから、思慮が足りていなかったねえ :zany_face:
=> ChannelGroupWebhook に user_id を足す

app/controllers/channel_group_webhooks_controller.rb, app/controllers/my/notification_settings_controller.rb, app/models/channel_group_webhook.rb, app/models/concerns/slack_block_builder.rb, app/models/notification_webhook.rb, app/models/user.rb, app/views/channel_groups/show.html.erb, app/views/my/notification_settings/index.html.erb, config/routes.rb
これまでも動作していたものの UI がなかった ChannelGroupWebhook の UI を、ようやっとつくります :joy:
=> ChannelGroupWebhook を追加・削除する UI を実装する

app/assets/config/manifest.js
=> mission_control-jobs 関連の assets を明記してやらないとエラーになるみたい

app/controllers/channel_groupings_controller.rb, app/views/channels/show.html.erb, config/routes.rb
=> Channel GroupからChannelを外せるようにする

Dockerfile, Gemfile, Gemfile.lock
Rails 8 になったし、Ruby も最新の 3.3.6 を使ってこ :up:
=> Ruby 3.3.6

app/controllers/channel_groups_controller.rb
Channelの多いChannel Groupsも全部表示できるようになりました🚀
=> Channel GroupsページのChannels表示数を上限20から制限無しにした

app/controllers/my/unreads_controller.rb, app/models/user.rb
- https://github.com/kairan-app/feeeed/issues/332
に対応します :v:
=> UnreadsページのChannelGroupナビには、ownしているものだけではなくjoinしているものも並べる

app/assets/stylesheets/application.css, app/views/channels/_with3items.html.erb, app/views/pawprints/_blocks.html.erb
PawprintやItemによって差が出るスペースが気にならなくなるように、白い敷物を削除しました🚀
=> トップページの白い敷物を削除

app/controllers/users/pawprints_controller.rb, app/controllers/users/subscribed_items_controller.rb, app/views/users/pawprints/index.atom.builder, app/views/users/pawprints/index.json.jbuilder, app/views/users/subscribed_items/index.atom.builder, app/views/users/subscribed_items/index.json.jbuilder, config/routes.rb
アルファ・リリースの協力者さんからお話があり、ためしに提供してみることにする。アルファもアルファなので仕様が変わることもありそうです。まずはミニマムな形での実装でやってみる :v:
=> 一部のデータを Atom や JSON で返してみる試み

app/controllers/sessions_controller.rb
現在、いちおうアルファ・テスト期間ということで、こちらで許可した人のみSignupできるようにしています。そのための制御を環境変数ALLOWED_USERSを使って行っていますが、既存のロジックだと、許可リストがひたすら膨らんでいくことになります。
なので、すでにSignupが済んでいる場合はALLOWED_USERSによるチェックを行わないようにします。これで「今からアルファ・テストに招待する人たち」のみをALLOWED_USERSで管理すればよいことになります。うれしい！
=> 新規登録のときのみALLOWED_USERSのチェックを行う

Dockerfile, Gemfile, Gemfile.lock
=> Ruby 3.4.1

app/views/channels/show.html.erb, app/views/items/_pawprint.html.erb
- https://github.com/kairan-app/feeeed/issues/372
=> URLのような空白文字なしの長い文字列を扱うときに、適切に折り返し処理したい

.github/workflows/test.yml, test/models/channel_test.rb
- Resolve https://github.com/kairan-app/feeeed/issues/175
=> 自動化テストをGitHub Actionsで動かす

app/views/about/index.html.erb
https://github.com/kairan-app/feeeed/issues/381 の件、取り急ぎPRを作成しました🚀
まずは最低限「誰が作ってるか」くらいの情報で、体裁もAboutの一番下にくっつけたという感じです。
（ゆくゆく、もう少し詳しい記載などしていっても良いかなと思っています）
@juneboku 
文面などシンプルに作ってみましたが、加筆修正などありましたら何なりといじっていただけると嬉しいです！
=> Aboutページに開発者情報を追加

app/controllers/my/unreads_controller.rb, app/models/item.rb, app/views/my/unreads/show.html.erb
- https://github.com/kairan-app/feeeed/issues/387 :link:
=> UnreadsページのItemに概要文を少し表示してみる

app/controllers/channels_controller.rb, app/controllers/my/pawprints_controller.rb, app/models/item.rb, app/models/pawprint.rb, app/views/channels/_search_form.html.erb, app/views/layouts/_menu.html.erb, app/views/my/pawprints/index.html.erb
日々、Pawprintを貯めていくと大事なデータになっていくので、そこを対象に「あれ、なんだっけな〜」をテキスト検索によって掘れるようになるといいかな、と考えました :bulb:
=> My Pawprintsをテキスト検索できるようにするぞ

app/views/layouts/_menu.html.erb, app/views/my/owned_channels/pawprints/index.html.erb, app/views/my/pawprints/index.html.erb, app/views/pawprints/index.html.erb, app/views/shared/_pawprints_header.html.erb
- https://github.com/kairan-app/feeeed/pull/405
の作業のときに少し散らかしてしまったので、ここでいったん整理してみます。みなさんに使ってもらってフィードバックが出てきたらまたあらためて見直したりします :v:
=> Pawprintsのページにnavを置いてサイト構造とメニューを整理する

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/417
をやったことで、さらっとChannelの情報が更新され得る状況になったので、変化に気付けたらうれしいこともあるかな〜と思い、通知処理を仕込んでみます :bell:
=> Channelが保存されたらDiscoで通知する

app/assets/stylesheets/application.css, app/controllers/users_controller.rb, app/views/about/index.html.erb, app/views/channel_groups/_flex_cards.html.erb, app/views/channel_groups/_grid_cards.html.erb, app/views/channels/_flex_cards.html.erb, app/views/channels/_grid_cards.html.erb, app/views/channels/_with3items.html.erb, app/views/items/_cards.html.erb, app/views/my/index.html.erb, app/views/my/unreads/show.html.erb, app/views/pawprints/_blocks.html.erb, app/views/pawprints/_lines.html.erb, app/views/shared/_pawprints_header.html.erb, app/views/users/index.html.erb, app/views/welcome/index.html.erb
ちょっとずつTailwind CSSに寄せていくね〜 :wave:
=> application.cssからTailwind CSSに移行する - h2 h3編

app/assets/stylesheets/application.css, app/views/channels/preview/show.html.erb, app/views/layouts/_menu.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
- https://github.com/kairan-app/feeeed/pull/423
の続きで、今回はulをやっていきます :dizzy:
=> application.cssからTailwind CSSに移行する、ul編

app/controllers/feeds/channel_groups_controller.rb, app/views/feeds/channel_groups/index.atom.builder, config/routes.rb
- https://github.com/kairan-app/feeeed/issues/427 が経緯
- https://github.com/kairan-app/feeeed/pull/428 のChannelGroup版
=> 新着ChannelGroupをAtomで返す

app/controllers/feeds/channel_groups_controller.rb, app/controllers/feeds/channels_controller.rb, app/controllers/welcome_controller.rb
とくにトップページの「Recent Channels」のところの並び順を見直したい :bulb:
=> いくつかの箇所のorderを整理する

bin/create-worktree.sh
開発においてGitのworktreeを活用していこうと思いまして、このリポジトリでworktreeをつくるならこうかな、という内容をスクリプトにします :technologist: :dash:
=> 作業用のworktreeをつくるスクリプトを用意する

app/controllers/channels_controller.rb, app/views/channels/show.html.erb, config/recurring.yml
- 最後に新着Itemをチェックしたのはいつか
- w曜日のh時台、という重点チェック時間帯があれば、それを
表示させます :muscle:
=> Channelページに更新情報を載せる

app/controllers/welcome_controller.rb, app/models/channel.rb, app/models/channel_group.rb, app/models/pawprint.rb, db/migrate/20250713045516_add_performance_indexes_to_tables.rb, db/schema.rb
- https://github.com/kairan-app/feeeed/pull/461
に続いて。ボット等がアクセスしてくるのはトップページが多くて、ここのパフォーマンスが悪いとアプリケーション全体のパフォーマンスに悪影響があるとわかったので :pray:
=> トップページのパフォーマンスを改善したい
