kairan-app/feeeed

db/migrate/20240127123627_create_channels.rb, db/schema.rb
Rails のお作法に則るなら新規の Migration ファイルを追加するところだけど、まだぼくの手元にしか環境がなくて Rollback も容易なので、過去に遡って定義を編集することにします。
=> Channel モデルのテーブルスキーマを調整する

app/jobs/item_creation_notifier_job.rb, app/models/channel.rb
特に新規の Channel を登録したとき、初回のフルスキャンで Item がまとめてたくさん保存されるので、通知が爆発する :bomb:
- 同じ Channel 内の Item であれば、一度通知したあとはクールダウン・タイムを設けてみる
- 「新着 Item の情報を一通り揃えてから一気に保存」としていたが「ひとつの Item の情報を揃えたら保存」と逐次で保存を行うようにする
- 間に sleep も入れておく
=> 新着 Item の保存通知がドバッと発生しないように工夫する

app/jobs/item_creation_notifier_job.rb
ポッドキャストのフィードにはしばしば全エピソードの情報が含まれて、数百の Item を処理していると 10 分間以上を要することがある :timer_clock:
=> Channel 登録時の Item 取得に 10 分間以上かかることがあるとわかったので、判定ロジックを見直す

app/jobs/item_creation_notifier_job.rb, app/models/channel.rb, app/models/channel_stopper.rb, app/views/channels/show.html.erb, db/migrate/20240211092319_create_channel_stoppers.rb, db/schema.rb
- https://github.com/kairan-app/feeeed/issues/28
- ChannelStopper モデルを導入する
- Stopper がくっついている Channel は更新処理の対象から外す
- 更新停止中の場合は Channel ページにその旨を表示する
=> Channel の更新停止を表現する ChannelStopper モデルを実装する

app/models/channel.rb, app/views/channels/_table.html.erb, app/views/items/_table.html.erb
スタイリングしていく上で favicon を便利に使えるシーンがあるかもしれないので、試験的に表示してみます :test_tube:
=> Channel 情報のひとつとして favicon を表示してみる

app/models/channel.rb, app/models/item.rb, app/views/channels/_cards.html.erb, app/views/items/_cards.html.erb
Channel と Item の image_url は nil の場合があります。これによってスタイリングの難易度は上がると思うので、仮に「画像は必ず存在するものとする」としたらスタイリングしやすくなるのか？を検証するための、実験的変更です :test_tube:
@sugiwe さんから見て「こういう方がいいね」となるならそのまま使ってもらって「画像があってもなくてもピシッとやりまっせ」となるなら、この変更はあとから破棄してもらっても大丈夫です :wink:
https://placehold.jp/rule.html
> 料金について
> 当Webサイトのサービス利用料は無料です。
>
> 禁止事項
> 当Webサイトに過剰にアクセスすること。
>（サーバーが負荷でハングアップするぐらいでなければ特に問題ありません。）
=> Channel/Item の画像がない場合はプレイスホルダを表示する

Gemfile, Gemfile.lock, app/models/channel.rb, lib/open_graph.rb
フィードの中では https://example.com/article1 を示していても、実際にアクセスすると https://example.com/article1/ のように末尾スラッシュありのページにリダイレクトされたりする。ってことがわかった。
FaradayMiddleware の FollowRedirects を使って、リダイレクトされる場合にも対象サイトの情報を取得できるようにする。
og:image のパース方法を変えたら、今まで情報を取得できなかったサイトでも取得できるようになった (？)
=> OpenGraph クラス、リダイレクトを追従して og:image をもっと取れるように

app/models/channel.rb
- URL に全角文字を含むものを URI.parse に渡すと URI::InvalidURIError が発生する
- フィードの中に、エンコードされていない URL が設定されているケースがあるとわかった
=> Item#url は、先にエンコードしてから処理する

app/jobs/item_creation_notifier_job.rb
- https://github.com/kairan-app/feeeed/pull/13
Channel は登録できたが、なんらかの理由で Item の保存はうまくいかないケースがある。処理を調整して Item の保存がうまくいくようになると、全 Item の分が Discord に通知されてしまってたいへんなので、同じ Channel からの Item 通知は 5 件まで、という制御を入れてみるぞ :dash:
=> 新着 Item の通知処理をもっともっといい感じにしたい

app/jobs/application_job.rb, app/jobs/channel_items_updater_job.rb, app/jobs/item_creation_notifier_job.rb, config/initializers/sidekiq.rb, config/routes.rb, config/sidekiq.yml
- ログを見ていて「リトライしすぎでは？」と思うことがあったので、設定を見直したい
- sidekiq/web を Production 環境でも有効にする (認証は設定する)
これでウェブのダッシュボードにアクセスできるようになるので、様子を見ながら運用していこ〜 :nerd_face:
=> ActiveJob と Sidekiq の設定をそれっぽくする

app/controllers/channels_controller.rb, app/controllers/items_controller.rb, app/controllers/my/inbox_controller.rb, app/controllers/welcome_controller.rb, app/views/channels/show.html.erb
同一 Channel 内の Item で published_at が同じものがあるとき、どっちを先に表示したらいいか判断がむつかしい。ポッドキャストのエピソードの場合は title の先頭にエピソード番号が入ることも多いから title DESC ってことにしてみるか。
=> Item の published_at が同じ場合に備えて title でも order しておく

app/controllers/sessions_controller.rb, db/migrate/20240224150007_add_google_guid_column_to_users.rb, db/schema.rb
とりあえずで実装した Google 認証では、アカウントのキー情報をメールアドレスにしていた。これだと、利用者がメールアドレスを変更したときに (今はまだメールアドレスの変更機能はないけど) Google アカウントとの紐付けが破綻してしまう。
なので、まじめに ID っぽい情報をキーとして扱うようにします。
>これらのクレームを取得した後、aud クレームにアプリのクライアント ID の 1 つが含まれていることを確認する必要があります。含まれている場合、トークンは有効で、クライアント用のものであるため、ユーザーの一意の Google ID を sub クレームから安全に取得して使用できます。
>https://developers.google.com/identity/sign-in/web/backend-auth
によれば、payload に含まれる「sub」という項目が一意の Google ID に相当するとのことで、これを保存することにします。
Production 環境では、この ID を保存せずにログインさせてしまっているので、利用者の全員の ID をデータベースに収集するまでは今回追加するカラムに NOT NULL 制約をかけることができません。
- この Pull Request をマージして、Production 環境で db:migrate を行う
- すべての利用者にログアウト→ログインを行ってもらう
- 追加の Pull Request でカラムに NOT NULL 制約や UNIQUE 制約を適切に設定する
といった順番で進めていくつもりです。今後ログインする利用者については、初回ログイン時に ID を必ず保存するのでなにも問題はありません。
=> Google のアカウントを一意に特定する ID を保存する

app/assets/stylesheets/application.css
フォント設定がない状態だとiPhone Safariで明朝体で表示されるので、ひとまずゴシック系でよしなに表示される設定だけしてみました🎨
=> スタイリング @ 2024-03-04

Gemfile, Gemfile.lock, lib/open_graph.rb
https://note.com/fukkyy/rss というフィードに含まれる Item に https://note.com/fukkyy/n/n4166e9e642b0 という link を持つものがあり、これに Faraday からアクセスして情報を取得しようとすると too many redirects でエラーとなってしまう問題があった。
```
/usr/local/bundle/gems/faraday_middleware-1.2.0/lib/faraday_middleware/response/follow_redirects.rb:83:in `block in perform_with_redirection': too many redirects; last one to: https://note.com/cd/sessions?redirect_to=https://comemo.nikkei.com/n/n4166e9e642b0&m=G%2BXI03QNhsPd9V2G1HmceWLNde/6kFVoy/3npJ/sI5zRNS5F9hPxYKevYoXNnlfx (FaradayMiddleware::RedirectLimitReached)
```
もともと follow redirects する処理にはなっていたが、note.com のセッション管理があって、クライアントサイド Cookie を受け入れないと延々とリダイレクトされてしまうようだった。
クライアントサイドを Cookie を受け入れる :cookie:
=> Cookie を受け入れながら Faraday で get する

app/models/channel.rb
- https://github.com/kairan-app/feeeed/issues/53
たとえばブログのフィードにおいては、entry つまり記事が url を持っていない状況は想定しにくい。のだけれど、ポッドキャストのフィードにおいては entry の url は必須という雰囲気じゃなくて、音声ファイルのパスが enclosure url に設定されていればいいじゃん、というノリ。ポッドキャストのクライアントアプリは音声ファイルを再生できればよくて、そのエピソードに固有のウェブページがなくてもぜんぜん困らないもんね。
それくらいのノリなので、entry url が nil な場合は Channel の site_url を代わりに使うことにしてお茶を濁すぞ！だいたいの場合において、大した問題にならなそう〜。
「やっぱりこれじゃダメだよね」ってなったら Item モデルのスキーマから考え直します :dash:
=> フィードの中の entry が url を持っていない場合は、Channel の site_url で代替する

app/models/channel.rb
動画ページにアクセスして og:image の値を取得する方式だと、ちょいちょい下の画像になっちゃうようなので :sweat_smile:
=> YouTube の場合は Video ID から画像 URL を生成する

app/jobs/item_creation_notifier_job.rb, app/jobs/reaction_creation_notifier_job.rb, app/models/item.rb, app/models/notification_webhook.rb, app/models/reaction.rb
通知処理ごとに embed のデータを組み立てていたので、Discord 上の表示がばらばらになっていました。メソッドにして共通化することで「Item は Item の見た目」「Reaction は Reaction の見た目」で整えていきます :sparkles:
=> Item/Reaction の Discord 通知用の embed を組み立てる処理をメソッドにして共通化する

app/views/items/_pawprint.html.erb
世界がそれを Reaction と呼んでいたころに実装されたコードがあり
- https://github.com/kairan-app/feeeed/pull/70
これじゃあ Unpaw のボタンが動かないってことがわかったので直した。っていうか、実装当時にこれは本当に動いていたのか？ :thinking:
=> Unpaw ボタンが壊れているっぽいので直したい

app/models/notification_webhook.rb, db/migrate/20240323063928_add_mode_column_to_notification_webhooks_table.rb, db/schema.rb
- これまでの NotificationWebhook は「自分の直近の Pawprints を対象とする」動作モードしかなかった
- 最初に試運転したいのがそれだったので、まずそれを実装した
- ここで mode というカラムを追加して、動作モードを選べるようにしていく
- これまで試運転してきたやつは `my_pawprints` とする
- このあと `my_subscribed_items` という動作モードを追加するつもり
- もともと話していた通り「自分が購読している Channels の新着 Items を対象とする」動作モードを実装する準備
=> NotificationWebhook に mode を追加し、自分の Pawprints 以外も扱えるようにしていく

app/models/notification_webhook.rb
- https://github.com/kairan-app/feeeed/pull/106
の続き。これでモードが 2 種類になるぞい。ついでに、Pawprints や Items の並び順を制御するために find_in_batches をやめて each_slice を使う実装に変えています。
=> NotificationWebhook に、購読している Channel の新着 Item を通知するモードを実装する

app/controllers/channels_controller.rb, app/controllers/notification_webhooks_controller.rb, app/controllers/ownerships_controller.rb, app/controllers/subscriptions_controller.rb, app/jobs/item_creation_notifier_job.rb, app/jobs/pawprint_creation_notifier_job.rb, lib/disco.rb
下記のイベントを Discord に通知するように処理を追加します :v:
- 利用者が Channel を登録しようとしたとき
- 利用者が Channel を Subscribe するとき
- 利用者が Channel を Add to my own するとき
- 利用者が NotificationWebhook を追加するとき
それに先立って、Discord 通知用のモジュールを導入し、既存の通知処理を整理します :muscle:
=> 運用者向けに種々のイベントを Discord に通知する

app/jobs/item_creation_notifier_job.rb
もともと Development と Production で同じチャンネルに通知していて、そのときに見分けがつくといいな〜と思って Rails.env の情報を付与していました。
しかし、開発が進んでからは、Development での通知は自分だけがアクセスできるチャンネルに向けることでチームメンバーに影響を与えずに済むのでそっちの方がいいねってことで定着しています。なので Rails.env を抜いてみます。
=> 新着 Item の Discord 通知にて、Rails.env の情報はナシでいいか

app/assets/stylesheets/application.css, app/views/items/_pawprint_form.html.erb, app/views/my/unreads/show.html.erb
コミットメッセージの通り、UnreadsページのレイアウトをPawprintsページに寄せる形で調整してみました🎨
Skipボタンの位置は悩ましいのだけど、ひとまず整理してここかなという位置に…！
この調整を皮切りに、トップページでも Channel & Item のセットで表示するようにしたり、 Unreads ページで juneboku さんがセットしてくれた Paw 画像を別のページでも使ったり、というのを後日やっていきたい🚀
=> Unreadsページのスタイリング

app/assets/stylesheets/application.css, app/views/channels/_search_form.html.erb, app/views/layouts/_google_login.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/application.html.erb
あまりの大改造で模索しながら進めたためコミットを分けることもできず、1コミットでめちゃくちゃ変えてしまいました…🫣
ざっくり変更内容は以下となりますっ
- サイドメニューを廃止
- 左下のログインボタン＆ログイン後のアイコン表示を廃止
- rururu ロゴ含め、ヘッダーにナビゲーションを集約
- ロゴと Channelサーチは左上、右上にその他を設置
- ログイン後は、右上にいくつかのメニューとアイコン（アイコンクリックでさらにメニュー表示）
- スマホ用にフッター下部にタブを設置
- 元々サイドバーにずらっと並べていた全ページへのリンクは、一旦開発者向け的にフッターに逃して配置（最終的には無くしたり必要はものは残したりしても良さそう。あと利用規約とか細かい静的ページを置くことも見越してのフッターエリア作成でした）
=> メニューまわり大改造🚀

app/assets/stylesheets/application.css, app/controllers/welcome_controller.rb, app/views/items/_pawprint.html.erb, app/views/my/unreads/show.html.erb, app/views/welcome/index.html.erb
トップページにある Channels 一覧と Items 一覧の代わりに、「1 Channel あたり最大 3 Items が格納されたコンポーネントを10個ほど表示（並び順は、 Item の created_at をキーに）」させたい。
…のですが、力不足で controller での設定が失敗しており意図した表示になっていない状態です😭
意図した表示では無いのですがスタイリングだけ進めて Draft PR の形でプッシュさせていただきました、 controller のところを見てもらえると嬉しいです🙏
=> トップページに Channel & Items のコンポーネントを表示させる

app/assets/stylesheets/application.css, app/views/layouts/_menu.html.erb, app/views/my/index.html.erb, app/views/my/unreads/show.html.erb, app/views/welcome/index.html.erb
引き続き気になるところのスタイリング🚀
- 前回、アイコンを細いバージョンに変えたに伴う不具合がいくつかあったので修正
- スマホでのマイメニュー（My Pawprintsなど）のアイコンが崩れてたので修正
- Settingページのアイコン（My Profileなど）が消滅してたので蘇生
- 前回MTGで出た、トップやUnreadsページでのリンク領域を広げてクリック（タップ）しやすくした
- その他細かいスタイルの調整
=> スタイリング @ 2024-04-19

app/jobs/item_creation_notifier_job.rb, app/jobs/pawprint_creation_notifier_job.rb, app/models/channel.rb, app/models/item.rb, app/models/notification_webhook.rb, app/models/pawprint.rb
既存の Discord 向け新着 Item 通知との違いは、下記の通り :dash:
- Discord の embeds の代わりに Slack の blocks にあわせて JSON を組み立てる
- Item ひとつずつではなく、Channel ごとに Item をグルーピングして処理する
=> Slack 向け新着 Item 通知を実装する

app/controllers/channels/fetch_controller.rb
- 運営向けの Discord 通知処理を入れる
- 末尾の空行が 2 行あったので削る
=> Channels::FetchController、運営通知を入れて末尾の空行を削除する

app/models/channel.rb, app/models/concerns/stripable.rb, app/models/item.rb
新着 Item の Slack 通知を見ていたら、表示が意図した通りになっていないものを見つけた。なんぞ？
見ていたら、The HEADLINE の Channel と Item の文字列カラムには、先頭・末尾に空白文字が入ってしまっているっぽかった。なるほどね〜〜。
```
#<Channel:0x00007f57ece336e0
id: 199,
title: "The HEADLINE",
description: "\n      The HEADLINE RSS\n    ",
site_url: "https://www.theheadline.jp",
feed_url: "https://www.theheadline.jp/rss/feeds.xml",
image_url: "https://d2bz98p2lfzf5b.cloudfront.net/GbHwg5yhkd3d78ds5vXtrfML",
created_at: Mon, 18 Mar 2024 17:59:06.059555000 JST +09:00,
updated_at: Mon, 18 Mar 2024 17:59:06.059555000 JST +09:00>
#<Item:0x00007f57ecc99af0
id: 24255,
channel_id: 199,
guid: "https://www.theheadline.jp/articles/1060",
title: "\n        Meta の詐欺広告問題、日本は「なめられている」のか？前澤氏・堀江氏ら批判\n      ",
url: "https://www.theheadline.jp/articles/1060",
image_url: …
```
=> 先頭や末尾に空白文字が入っちゃうケースがあるので、データベースに保存する前に strip する

docker-compose.yml
`docker-compose up` したときに
```
WARN[0000] /path/to/ghq/src/github.com/kairan-app/feeeed/docker-compose.yml: `version` is obsolete
```
と表示されると気が付いた。調べてみると version は単純に書かなきゃいいってことなので、消します！
https://docs.docker.com/compose/compose-file/04-version-and-name/
=> docker-compose.yml の version はもう書かなくていいみたい

app/models/channel.rb, app/models/concerns/validation_errors_notifiable.rb, app/models/item.rb
@sugiwe さんの 2024-05-02 の日記が、Validation に引っかかって Item として保存できていないことに気付きました :sob:
制約を見直して保存できるようにする対応はこのあとすぐにやるのですが、その前に、事象に気付けていない体制がまずい (これまで、他にも保存できていないものがあったと想像される) ので、通知を実装しておきます :pray:
=> Channel や Item の保存失敗時に運営 Discord に通知する

app/models/item.rb, db/migrate/20240503013247_make_items_guid_longer.rb, db/schema.rb
掲題の通りで、むしろ「なんで最初からそうしていなかったの？？？」という @juneboku の凡ミス :sob:
実際に guid が長くなる Item の保存に失敗していると @sugiwe さんが気付いてくれたおかげで修正につながりました :pray:
=> Item の guid には URL を入れるケースがあるので、長さ 2083 まで許容したい

app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/171
によって通知を入れたことで、Item を保存しようとして title がなくて Validation に引っかかるケースがちょこちょこあることが判明した。そうだったのか〜。
https://validator.w3.org/feed/ にて title なしの entry を持つようなフィードを検証してみると、title がないと Invalid という判定になった。仕様では entry に title を要求しているんですね。
であれば、rururu は「迷ったら仕様に従う」として、title がないものは無視しますよ、というスタンスで進めてみようと思います。もちろん、title 以外の情報から適当に title っぽい文字列を決めてあげれば保存はできるわけですが、それは Invalid なフィードの存在をイネーブリングすることにはなるので、望ましい対応ではないと考えました。
議論の余地はあると思うので、別の意見があればぜひコメントください！ :wink:
=> フィードの中の title が設定されていない entry は無視する

app/models/channel.rb, app/models/concerns/empty_strings_are_aligned_to_nil.rb, app/models/item.rb
Channel の image_url が nil なら img タグを出力しないはずだけれど、これはなんじゃろう？と思って。
データを見てみたら image_url が nil ではなくて空文字列であった。うーむ、なるほどね！
これはウェブアプリケーションを開発・運用している全員の悩みという気もするな… すでにベスト・プラクティスが存在しそうなトピックではあるけれど、自前で「こんな感じかな…？」という手を打ってみます。もっといい方法が見つかったらすぐに乗り換えるぜ :muscle:
```rb
> Channel.where(description: "").count
=> 0
> Channel.where(description: nil).count
=> 37
> Channel.where(image_url: "").count
=> 1
> Channel.where(image_url: nil).count
=> 35
> Channel.where(site_url: "").count
=> 0
> Channel.where(site_url: nil).count
=> 1
```
=> モデルにおいて、空文字ならnilにして保存してほしいカラムを指定しておく

app/controllers/channels_controller.rb, app/controllers/info_controller.rb, app/controllers/items_controller.rb, app/controllers/sessions_controller.rb, app/views/info/index.html.erb, config/routes.rb
- 許可リストに登録されていない人がログインしようとしたら、Info ページにリダイレクトする
- Info ページには「アルファ・テスト中で、利用登録は受け付けていないよ」を説明する
- Channel 一覧 / Item 一覧のページ当たりの表示件数は、なるべく約数の多い数にしておいて見栄えを少しよくする
=> アルファ・リリースに向けて、なにも知らん人が見にきたときのナビゲーションを整えておく

app/controllers/my/unreads_controller.rb, app/views/my/unreads/show.html.erb
今は params で指定しないとデフォルトの 3 になっちゃっていたんだけど、session に保存するようにして、各利用者にとってのちょうどいい日数を見つけてもらいやすくなるといいな〜の気持ちです :v:
=> Unreads ページの対象抽出さかのぼり日数を session に保存する

app/assets/stylesheets/application.css, app/views/channels/preview/create.html.erb, app/views/channels/preview/show.html.erb, app/views/info/index.html.erb
主に以下を行いました🚀
- Infoページのマークアップとスタイリング
- Previewページのマークアップとスタイリング（一応、既存Channelが複数あっても成立するように）
- 注意事項部分などの文面追加
文面は、前に [notion](https://www.notion.so/june29/2e8d3416863b4801a3d584bb56086f2c) の「フィード登録にあたっての注意事項」で作った文面をもとに入れてみました。
例は2つほどあるとわかりやすいかなと思ったので Yahoo!ニュースと NHKオンライン（新たに見つけた）を入れてみました。
あとはちょっと思いつきですが、「rururuで自動検知はできないけど、まずいものがあったら手動で消すからね」という文面も入れてみました！
（こういう注意書きのようなものって、入れれば入れるほどフィード登録のモチベーションを削いてしまうのではと一瞬思ったのですが、ノーブレーキであとから問題になる方が圧倒的に良くないので、適切に入れておくの大切ですね🗽）
=> スタイリング @ 2024-05-07

app/models/user.rb, db/migrate/20240510075930_make_users_name_longer.rb, db/schema.rb
開発の初期になんとなく 2 〜 15 文字という制約を設定していたが、これだと Gmail のローカルパートが 16 文字以上の人は Signup 失敗してします :innocent:
当面は Google ログインでいくので、
> ユーザー名は 6～30 文字で指定してください。
> [ユーザー名の作成 \- Gmail ヘルプ](https://support.google.com/mail/answer/9211434?hl=ja)
に従って 30 文字まで許容します :v:
=> User#name は 30 文字までオッケーとする

app/assets/stylesheets/application.css, app/views/pawprints/_lines.html.erb
Pawprintsページにて各アイテムの画像とチャンネルリンクを追加しました🎨
特に、チャンネルリンクを追加したことで、これまで「他ユーザーさんのPawprintsきっかけで自分がPawする」にあたっての動線が非常に難解だったのを少し改善できる見込みです。
ゆくゆくは、Pawprintsページから直接「追いPaw」できるようにしたい🚀
=> Pawprintsページのプチ改善

app/models/channel.rb, db/migrate/20240603083752_add_data_column_to_items_table.rb, db/schema.rb
- https://github.com/kairan-app/feeeed/issues/135
- https://github.com/kairan-app/feeeed/issues/193
を考える中でフィードの Entry の中の enclosure_url を Item に保存したいと考えた。ミニマムの一手として Item モデルに enclosure_url カラムを生やす案が浮かぶが、これだと扱いたいデータが増えるたびにカラム追加を行うことになるし、すでに保存されている Item の分をさかのぼってデータ取得しようと思うとなかなかたいへんだ、と気付くに至った。
そこで、フィードの Entry 情報をまるごと JSON にして突っ込んでおく data カラムを用意し、これからフェッチする分については生データに近い情報を保持しておくことにする。こうすれば、いつかの未来に「このデータも活用したい」となったときにすぐに活用できるようになる。わいわい。
=> Item にフィードの Entry の情報をまるごと保存する

Dockerfile, Gemfile, Gemfile.lock
Ruby の 3.3.2 がリリースされたので、さっそく使います :gem:
=> Ruby 3.3.2

app/assets/stylesheets/application.css, app/controllers/my/unreads_controller.rb, app/models/item.rb, app/models/user.rb, app/views/my/unreads/show.html.erb
- https://github.com/kairan-app/feeeed/pull/198
によって Item モデルに enclosure_url と enclosure_type の情報が保存されるようになったので、これを活用して Unreads ページに audio/video/text を分けて表示するモードを実装してみます。
=> Unreads に audio/video/text のフィルタを実装する

app/controllers/sessions_controller.rb
アルファ・テスト期間の場当たり的な対応という感じ :zany_face:
利用者が自由にプロフィールアイコンを変更できるようになったらまるごと見直し対象になるでしょう :dash:
=> Google アカウントのプロフィールアイコンが変わったときは追随するが、別の画像が登録されている場合には上書きしない

app/assets/stylesheets/application.css, app/views/my/unreads/show.html.erb, app/views/pawprints/_lines.html.erb
下記を進めましたっ🍖
- Pawprintsページでも Audio Player を表示
- 上記に伴い、Unreadsページの Audio Player レイアウトを Paw 側から Item 側に移動
- Unreads ページのタブが、一番上のチャンネルだけにかかっているように見えてしまっていたので修正
=> スタイリング @ 2024-06-19

app/jobs/channel_group_webhook_notifier_job.rb, app/models/channel_group.rb, app/models/channel_group_webhook.rb, db/migrate/20240618235702_create_channel_group_webhooks.rb, db/schema.rb
ChannelGroup にくっつけて、そこの新着 Item を Webhook で通知してくれる ChannelGroupWebhook モデルを導入します。ここでは
- テーブルのスキーマを定義する
- モデルを実装する
- Discord への通知処理を実装する
までを扱います。とりあえずこいつを Production 環境で動かしてみて、通知処理が期待通りに動くかを確かめます。
そのあとで ChannelGroupWebhook を作成するフォーム等を追いつかせていきます。
=> ChannelGroupWebhook モデルを導入する

app/models/channel.rb
説明がむつかしいが… この変更によって登録できるフィードが増えるのです :dash:
- フィードの中に「このフィードの URL はこれです」の情報が含まれていないケース
- 実例 https://www.city.matsumoto.nagano.jp/rss/10/list1.xml
- これはフィードとして invalid なので「うちでは扱えません」としてもいいのだけれど :relieved:
- フィードの中の「このフィードの URL はこれです」の前後に空白文字が入っているケース
- 実例 https://pages.d-sato.net/feed.xml
- `"\n    https://pages.d-sato.net/feed.xml"` みたいになっていると GET に失敗する
これらのケースに該当するフィードでも登録できるように、処理に工夫を加えます。独特の知見が貯まっていく… :thinking:
=> 入力として受け取った feed_url を採用する

app/models/channel.rb
おそらくエンコードのロジックが不完全で、URL にダブルクォートが含まれているとエンコード漏れでエラーを起こしてしまっていた。場当たり的に「ダブルクォートの場合は、こう！」という条件分岐を入れたけれど、ベターな方法がありそう :thinking:
=> Item の url にダブルクォートが含まれても大丈夫なように

app/assets/stylesheets/application.css, app/controllers/my/unreads_controller.rb, app/models/user.rb, app/views/my/unreads/show.html.erb
- https://github.com/kairan-app/feeeed/pull/199
で実装したコンテンツの形式で絞り込む機構を廃止します。今後は ChannelGroup ごとに分けて閲覧できれば十分ではないか、と考えています。
- https://github.com/kairan-app/feeeed/pull/198
で Item に情報を持たせるようにしてそれは残るので、audio タグによる音声の再生はこれからも可能です。
=> Unreads の all/text/audio のフィルタを廃止する

app/controllers/channel_groups_controller.rb, app/models/channel_group.rb, app/models/user.rb, app/views/channel_groupings/_form.html.erb, app/views/channels/show.html.erb, db/migrate/20240714141127_add_owner_id_to_channel_groups_table.rb, db/schema.rb
- これまで ChannelGroup は誰のものでもなかった
- 公共のものという感じで存在していて、誰もが自由に Join できる状態だった
- ここで User と ChannelGroup の間のリレーションを見直す
- Owner: ChannelGroup の唯一の主
- Editor: ChannelGroup の編集を行える人、Owner から権限を与えてもらう
- Member: ChannelGroup の情報を受信する人
- この Pull Request では「Owner」という概念を導入する
=> ChannelGroup の Owner という概念を追加する

app/models/channel.rb
https://anchor.fm/s/a19e5164/podcast/rss は、フィードとしては生きているのですが、どうもウェブサイト https://podcasters.spotify.com/pod/show/piupod は死んでいるようで、サイトの情報を確認しようとして 404 になっちゃうってんで、新着 Item の保存ができなくなっていました :cry:
- サイトが死んでいても、フィードが生きていれば新着 Item を扱えるようにする
- フィードの中に `<itunes:image />` タグがあればそいつの情報を優先して参照してやる
ってな変更を加えて https://anchor.fm/s/a19e5164/podcast/rss をなんとか扱えるようにします。ウェブサイトが死んでいてフィードだけ生きている、ってことがあるのだねえ。
=> Item の image_url の導出ロジックを見直す

app/assets/stylesheets/application.css, app/views/about/index.html.erb, app/views/channels/preview/_form.html.erb, app/views/channels/preview/show.html.erb, app/views/info/index.html.erb
下記をスタイリングしました！
- Channel Preview と Channel 追加のところで見出しやボタンの UI がリセットされていたところを調整
- About・Info のページで一部を Tailwind CSS 化
全体の影響が少ないところから、と思いAbout・Infoを少しいじりました。
しばらく手探りが続くかもしれませんが、見た目上おかしく無いように確認しつつ進めていければと思っています🚀
=> スタイリング @ 2024-07-24

docker-compose.yml
ルー大柴さんの語りみたいなタイトルになってしまったが、仕方あるまいて… :zany_face:
手元の Development 環境にて、docker compose up したら tailwindcss の service が「Gem が見つからん！」といって終了してしまった。たしかに、ちょっと前に以下のふたつをマージしたから bundle install しなきゃいけなくて、
- https://github.com/kairan-app/feeeed/pull/232
- https://github.com/kairan-app/feeeed/pull/233
でも `docker compose run --rm web bundle install` はさっき実行しなかったっけ？となった。ところで sidekiq の service は元気に動いていて、docker-compose.yml をあらためて見てみると、tailwindcss とは bundle の volume を共有していなかったじゃん、と気付いた。
これで解決するはず！
=> tailwindcss の service とも bundle の volume を共有しておく

app/assets/stylesheets/application.css, app/controllers/channel_skips_controller.rb, app/views/channel_skips/create.turbo_stream.erb, app/views/my/unreads/show.html.erb, config/routes.rb
主に、新規に Channel をアプリケーションに追加してそれを Subscribe したとき、その Channel のすべての Items の created_at が最近の日時になってしまって Unreads ページにも乗ってくる形になる。
仮にその Channel のフィードに 100 件の Items が含まれている場合 (ポッドキャストだとちょいちょいある)、過去の全 Items が Unreads ページに反映されてしまい、Skip しようにも 100 回のタップが必要になって煩わしい。
そこで Skip all items というリンクを導入し、指定の Channel のすべての Items を一撃で Skip できるようにしてみる。他にもっといい方法があればそれを採用するのだけれど、現時点で思い付いている中ではこれが妥当な案。
=> Unreads ページにて、指定の Channel のすべての Items を skip する機能を実装する

app/models/notification_webhook.rb, app/models/pawprint.rb
- https://github.com/kairan-app/feeeed/issues/235
の調査を進めていて気付いたことがあったので改善を試みます。Slack の Block Kit で組み立てたメッセージを投稿するとき、画像の URL に null を指定しまうと、どうも通知そのものが行われないようです。
Discord だと、画像の URL に null を指定しても通知自体は成功する (画像指定の部分だけいい感じに無視される) ので画像の有無による条件分岐をせずに Hash を組み立てていましたが、Slack 向けにはもうちょっと真面目に Hash を組んだ方がよさそうです。
=> Slack 通知、画像がないときのハンドリング

app/jobs/channel_items_updater_job.rb, app/models/channel.rb
- Itemのtitle等が更新されていたら追随したい
- Itemの情報取得ループに sleep を入れていたが、フィードに記載されている情報のみを参照する場合は sleep しなくてよい
=> Channel#fetch_and_save_items の処理をもうちょっといい感じにする

app/controllers/channels/fetch_controller.rb, app/jobs/channel_items_updater_job.rb, app/models/channel.rb
- https://github.com/kairan-app/feeeed/pull/274
の変更をやってみたら、ジョブキューに ChannelItemsUpdaterJob がどんどんたまるようになってしまった :innocent:
「Item の情報に変更があったら、検知して取り込みたい」と思ったものの、それを実現しようとすると新着 Item 更新処理の所要時間が長くなってしまうようだった。あれこれ工夫したいところだけど、まずは変更前の処理内容に近づけて、ジョブキューが詰まらないようにする :dash:
=> ChannelItemsUpdaterJob が詰まっちゃう問題をなんとかする

config/queue.yml
な〜んか solid_queue.yml の内容が反映されていない気がする、と思ったら、それもそのはず。
- https://github.com/kairan-app/feeeed/pull/271
を見たときに「へぇ、設定ファイルの名前が変わったのか〜」とは認識していたのに自分のアプリケーションで追随できていなかった。悲しい。でもまた少し Solid Queue と仲良くなれた感触もあって、それはうれしい。
=> Solid Queue v0.9.0 から、設定ファイルの名前は queue.yml に変わったのだった

app/jobs/item_creation_notifier_job.rb
ItemCreationNotifierJob の不備を見つけたので修正する :wrench:
- コメントと実装が合っていなかったので整える
- Item の guid を url で代用しているフィードの場合、新着を Discord に通知する処理が意図した通りに動いていないと気付いたので直す
- 新着判定のときはフィードに HTTP でアクセスするので、連続でアクセスしすぎないように sleep を入れる
- Channel モデルにフィードの内容をキャッシュするようにしてもいいかもなあ、と思った
=> Item の guid を url で代用している場合にも新着通知できるように

app/models/notification_email.rb, app/models/notification_webhook.rb
Rails 8 にしたら動かなくなっちゃったね、直します :wrench:
=> ActiveRecord の enum の書き方が変わったのであった

app/models/channel.rb, app/models/channel_group_webhook.rb, app/models/concerns/url_http_validator.rb, app/models/item.rb, app/models/notification_webhook.rb, app/models/user.rb
とある Item の image_url に URL としては invalid な文字列が保存されてしまい、ActionView::Template::Error が発生するに至った。
```
ActionView::Template::Error: The asset "【template_SNSサムネイル】" is not present in the asset pipeline. (ActionView::Template::Error)
```
https://feeeed.sentry.io/issues/6106414770/
URL 系のカラムにへんな文字列が保存されてしまわないように、まじめに validation をやるぞ！
=> 全モデルの URL 系カラムの validation を共通化する

config/application.rb
- https://github.com/kairan-app/feeeed/pull/323
にて Rails 8 系になったのはよかったけれど load_defaults が 7.1 を指していた (7.2 ですらなかった！) ので、気付いたこのタイミングでアゲアゲに上げます :up:
=> load_defaults を 8.0 にする

app/models/concerns/url_http_validator.rb
- https://github.com/kairan-app/feeeed/pull/337
で導入したロジックに意図しない挙動があり、image_urlがnilになるようなItemは保存できなくなっていました :sob:
UrlHttpValidatorではnilを許容して、nilにしたくないカラムについては別途で `presence: true` なvalidatesを記述してもらうのがよいでしょう。ってことで修正です :bow::dash:
=> UrlHttpValidatorにて、nilはオッケーとする

app/assets/stylesheets/application.css, app/views/items/_pawprint.html.erb, app/views/items/_pawprint_form.html.erb
- https://github.com/kairan-app/feeeed/issues/361 by @taizooo
- Pawprintのフォームのテキストフィールドをテキストエリアに変えて、表示上で複数行に渡るような長さの文字列も全容が表示されるようにする
- 際して、表示が崩れないように調整を行う
=> テキストフィールドをテキストエリアに変えて、長い文章を扱いやすくする

config/puma.rb, docker-compose.yml
https://github.com/rails/tailwindcss-rails?tab=readme-ov-file#puma-plugin にて案内されているものを使う。
そうすることで、Docker ComposeのServiceがひとつ減るのでリソースの削減になると期待している。記述量が少し減るってのも少しうれしいね。
=> Docker Composeに頼らず、Pumaのpluginでtailwindcss:watchする

app/controllers/pawprints_controller.rb, app/views/items/_pawprint.html.erb, app/views/items/_pawprint_form.html.erb, app/views/my/unreads/show.html.erb, app/views/pawprints/_blocks.html.erb, app/views/pawprints/_lines.html.erb, app/views/pawprints/create.turbo_stream.erb, app/views/pawprints/destroy.turbo_stream.erb
- https://github.com/kairan-app/feeeed/issues/366
- 一時期、Pawprintのフォームは2種類あって、そのための分岐も存在していた
- 今は1種類になったけれどコードベースには2種類あった時期の残骸が残っていたので一通り整理する
- PawしたらUnpaw用のフォームが表示されるようにして、利用者からはトグルっぽく見えるようにする
- このとき、もともとMemoに書いていた内容は保持されるように工夫する
=> Pawprintのフォームを整理して、どこからでもPaw/Unpawをできるようにする

app/controllers/channels/preview_controller.rb, app/models/channel.rb
- https://github.com/kairan-app/feeeed/issues/362
にて報告をいただいているように、Validなフィードがありながらそれを登録しようとするとうまくいかないケースが散見されています。Channel登録処理を見直して、ひとつでも多くのフィードをChannelとして保存できるようにします :muscle:
これまでは下記のように処理していました。
- `Feedbag.find(url)` してフィードのURLを探す
- 発見できたら、それを `Channel.add(feed_url)` に渡す
ですが、これだとうまく扱えないケースがあるってことがわかってきました。なので下記のように変えます。
- URLが与えられたら
- まずは `Feedjira.parse(url)` してみて、パース成功したらそのURLをフィードのURLとして扱う
- URLとしてValidなフィードのURLが与えられた場合は、これでうまくいく
- パース失敗したら `Feedbag.find(url)` であらためてフィードのURLを探してからパースを試す
- フィードじゃなくてサイトのURLを与えられた場合は、これで処理する
これで、今まで追加できていたパターンはそのままに、追加できなかったうちのいくつかは追加できるようになるはず :muscle:
=> 新規Channel登録の処理を改善する / Feedbag.findする前にFeedjira.parseしちゃう

app/controllers/channel_groups_controller.rb, app/controllers/channels_controller.rb, app/views/layouts/application.html.erb
いま、Googleにけっこうインデックスされていて「謎の情報集約サイト」のような印象を持たれがちになっています。われわれとしては「フィードリーダ」のつもりで、たまたま「Channelページ」がどんどん生成されて検索流入も生み出しているけれど、そこでページビューを増やしたいとも思っていないので、ためしにnoindexにしてみます :v:
@sugiwe さんとは合意済みです :muscle:
=> ChannelページとChannelGroupページはnoindexにする

app/controllers/channels/preview_controller.rb, app/models/channel.rb, lib/open_graph.rb
タイトルの通りです。これによって保存に失敗しているItemがいくつかあります。
The Open Graph protocol https://ogp.me/ としてog:imageに相対URLを入れることをどう扱っているかは理解しきれていないため、今回の対応が妥当かどうかは自信ナシ。どこかにタイミングで対応方針を変えることもあるかも！
=> og:imageに画像の相対URLが入っているとItemの保存にしちゃうので、絶対URLに変換してみる

app/models/notification_webhook.rb
これまで、NotificationWebhookのnotify系のメソッドは
- last_notified_atがnilのときは「6時間以内のPawprint/Item」を対象とする
- 通知するPawprint/Itemが0個だった場合はlast_notified_atを更新しない
となっていた。これで問題ないと思っていたのだけれど、
- 毎日00:00にnotifyを行う
- 18:00以降はアプリケーションを利用しない、というスタイルの人がいる
のふたつが組み合わさると「last_notified_atがnil」で「直近6時間以内のPawprintはない」という状況が続いてしまい、一向に通知が行われなくなってしまう。
- 直近6時間以内 → 直近24時間以内
- 通知するPawprint/Itemが0個だったときもlast_notified_atを更新する
=> NotificationWebhookの初回通知の処理を改善する

app/assets/stylesheets/application.css, app/views/channels/_flex_cards.html.erb, app/views/channels/_grid_cards.html.erb, app/views/channels/_with3items.html.erb, app/views/channels/show.html.erb, app/views/items/_cards.html.erb, app/views/my/unreads/show.html.erb, app/views/pawprints/_blocks.html.erb, app/views/pawprints/_lines.html.erb, config/brakeman.ignore
いま、アプリケーションの都合で指定した縦横比の領域にcoverするように画像を表示しているが、それだと縦横比が合わないときに上下か左右が切れてしまう。これをcontain式にして、ベターにできないか試します。
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/f8859bba-7892-47c9-a5b1-ff26e68d07fb) | ![after](https://github.com/user-attachments/assets/a6a86b0a-15fb-4be5-93de-ab4c5426d3c9) |
=> ChannelとItemの画像、見切れることなく表示できるとうれしいのであれこれ試す

app/jobs/channel_interval_adjustment_job.rb, app/jobs/channel_items_updater_job.rb, app/models/channel.rb, config/recurring.yml, db/migrate/20250701112401_add_check_interval_to_channels.rb, db/schema.rb, test/models/channel_test.rb
これまで、すべてのChannelを1時間ごとにチェックしてきたけれど、Channelが増えるほどにキューが大変になるのと、ほとんどのChannelにとってHourlyのチェックは贅沢なので、調整できるようにします :dash:
このあと、別のPull Requestで「このChannelは、水曜日の7:00に更新されることがほとんど」のようなケースに対応できるようにして、さらなる効率的な新着Itemチェックも模索したい考えがあります :bulb:
=> Channelごとに新着Itemチェックのインターバルを設定できるように

app/jobs/channel_items_updater_job.rb, app/models/channel.rb
いま、対象サイトにアクセスして400系だったり500系だったりするとログにスタックトレースがドカッと出て容量を食うので、もうちょっとコンパクトにロギングできるように一工夫を入れます :dash:
=> Channelの新着Itemチェック処理のエラーハンドリングをやる

app/models/channel.rb
具体的には https://feeds.megaphone.fm/guildtalk の各エピソードを保存できるようになります :v:
=> フィードのitemにlinkがないとき、enclosure_urlがあればそれを使う
